### ISSUE TITLE
POST to GET :/

### ISSUE THREAD

**Issue by alexdown** [kasisto/kasisto-server-api#3]
I read on https://github.com/kasisto/kasisto-server-api/blob/master/api-overview.md

> `POST /accounts`
> 
> **Get** customer accounts

POST to GET. uhmmmmmhhh :/

**Comment by bstewartny** [comment]
We decided to use POST for everything to keep it simple, and we need to send structured JSON parameters on many if not all methods.  POST to GET is OK IMO.
