### ISSUE TITLE
Subset of APIs for specific use-cases

### ISSUE THREAD

**Issue by G2Jose** [kasisto/kasisto-server-api#4]
I was wondering, what subset of the spec'd out APIs mentioned have to be implemented in order to simply enable a use case where a user can ask the bot for their account balance? Is Kasisto designed to work only if all endpoints are implemented, or can it work on a subset?

**Comment by bstewartny** [comment]
A sub-set of APIs can be implemented.  Non implemented APIs may return 404 or 501 status codes.  At minimum, "/accounts" end point must be implemented.

**Comment by RayBenefield** [comment]
Closing this ticket. If you have any more questions @G2Jose, please feel free ask. :)
